### PR TITLE
Fix/56/weird sheet behaviour

### LINKED ISSUE #56: Weird sheet behaviour since adding iCloud syncing
Since adding iCloud syncing (per #11), the following weird behaviour cropped up:

1. Open the app. From Home, tap "+" to bring up the "Add new budget" sheet
2. Background the app
3. Foreground the app. While iCloud syncs (presumably), the sheet will repeatedly dismiss and show itself a few times.

### PR DESCRIPTION
**Pull request by phlippieb**
Fixes #56

### CODE REVIEW

File: DailyBudget/DailyBudgetTests/DefaultInitializableTests.swift [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import XCTest
+@testable import DailyBudget
+
+final class DefaultInitializableTests: XCTestCase {
```
Comment (phlippieb) [inline DailyBudget/DailyBudgetTests/DefaultInitializableTests.swift:4]: UnitProvidingTests
