### PR TITLE
Fix home not updating when editing an expense

### LINKED ISSUE #39: Today's amount not updating when changed in budget view
Repro steps:

1. Given a budget with an expense
2. From the home view, tap to view the budget
3. Tap an expense and edit its amount
4. Note the updated daily amount in the budget view
5. Return to the home view. Note that the daily amount has not updated

### PR DESCRIPTION
**Pull request by phlippieb**
Resolves #39

### CODE REVIEW

File: DailyBudget/DailyBudget/Features/EditExpense.swift [hunk 1]
```diff
@@ -125,11 +129,13 @@ private extension EditExpense {
       expense.name = name
       expense.amount = isExpense ? amount : -amount
       expense.date = date
+      // TODO: signal to associatedBudget that it updated?
```
Comment (phlippieb) [inline DailyBudget/DailyBudget/Features/EditExpense.swift:132]:
```suggestion
```
